spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    banner-mode: "off"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    use_sql_comments: true
  flyway:
    baseline-on-migrate: true
    enabled: false
  datasource:
#    url: "jdbc:mysql://localhost:3306/db_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    url: "jdbc:log4jdbc:mysql://localhost:3306/db_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
#    url: "jdbc:log4jdbc:mysql://localhost:3306/db_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: "root"
    password: "123456"
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
    driver-class-name: "net.sf.log4jdbc.DriverSpy"
#    driver-class-name: "net.sf.log4jdbc.DriverSpy"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB


server:
  port : 8083
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include=*:

huawei:
  cloud:
    obs:
      accessKey: "KZGUMLJ5Z9MTEGBSVVQD"
      securityKey: "01nNSdo9au0koJ39DlEFhmYnFF5EUpExG8eLJ68O"
      region: "cn-east-3"
      bucketName: "lizheng-test"
    iam:
      domainUserName: "qq1323829945"
      username: "q1323829945"
      password: "300348sunline"
      projectId: "a7bbc97fa36648d4a9f4fea6d1534ab8"
    apig:
      appType: "MANAGEMENT"
      groupName: "loan_management"
      environmentName: "RELEASE"
      appName:
      ip: "139.9.123.142:8083"
      region: "cn-east-3"
      #todo
      domainUrl:

redis:
  server: 127.0.0.1:6379
  useCluster: false
  useSentinel: false
  password:

logging:
  level:
    cn.sunline.saas: trace
    jdbc:
      sqlonly: OFF
      audit: OFF
      resultsettable: OFF
      connection: OFF
      sqltiming: INFO
      resultset: OFF
    jdbc:
      sqlonly: OFF
      audit: OFF
      resultsettable: OFF
      connection: OFF
      sqltiming: INFO
      resultset: OFF
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss,SSS}] [%t] [%c]-[%p] %m%n"