package cn.sunline.saas.loan.model.enum

enum class Natures {
    ACT,LEG,ANE,ADV,SVC,PWN,LDG,MSE,MSV,MSR,MSF,BAN,INS,SBD,CON,REL,MED,ENT,SPO,GAM,HEA,SOC,EDU,AFS,TRA,
    AGY,BPO,SEC,HOU,COM,PUB,ICT,MFG,MFF,ART,CAR,JEW,WRT,REP,TRN,SHI,SEA,AGR,FOR,MIN,UTL,OIL,WAT,MIL,PAD,
    EMB,OTS,RLG,DFP,OGB,OGI
}