spring:
  main:
    banner-mode: "off"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true

server:
  port : 8083

management:
  endpoints:
    web:
      exposure:
        include=*:

datasource:
  default-datasource-url: "jdbc:mysql://localhost:3306"
  default-datasource-username: "root"
  default-datasource-password: "123456"
  default-datasource-database: "db_saas"
  default-datasource-option-flags: "useSSL=false&serverTimezone=UTC"
  default-datasource-driver: "com.mysql.cj.jdbc.Driver"
  tenant-datasource-url: "jdbc:mysql://localhost:3306"
  tenant-datasource-username: "root"
  tenant-datasource-password: "123456"
  tenant-datasource-option-flags: "useSSL=false&serverTimezone=UTC"
  tenant-datasource-driver: "com.mysql.cj.jdbc.Driver"