spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    banner-mode: "off"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    use_sql_comments: true
  flyway:
    baseline-on-migrate: true
    enabled: false
  datasource:
    #    url: "jdbc:mysql://localhost:3306/db_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    url: "jdbc:log4jdbc:mysql://localhost:3306/db_saas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: "root"
    password: "123456"
    #    driver-class-name: "com.mysql.cj.jdbc.Driver"
    driver-class-name: "net.sf.log4jdbc.DriverSpy"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB


server:
  port : 8082
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include=*:

redis:
  server: 127.0.0.1:6379
  useCluster: false
  useSentinel: false
  password:

logging:
  level:
    cn.sunline.saas: trace
    jdbc:
      sqlonly: OFF
      audit: OFF
      resultsettable: OFF
      connection: OFF
      sqltiming: INFO
      resultset: OFF
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss,SSS}] [%t] [%c]-[%p] %m%n"




#spring:
#  main:
#    banner-mode: "off"
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: none
#    generate-ddl: true
#    show-sql: true
#  flyway:
#    baseline-on-migrate: false
#    enabled: false
#
#server:
#  port : 8089
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include=*:
#
#datasource:
#  default-datasource-url: "jdbc:mysql://localhost:3306"
#  default-datasource-username: "root"
#  default-datasource-password: "123456"
#  default-datasource-database: "db_saas_loan"
#  default-datasource-option-flags: "useSSL=false&serverTimezone=UTC"
#  default-datasource-driver: "com.mysql.cj.jdbc.Driver"