apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsp-management
  labels:
    app: jsp-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsp-management
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate  
  template:
    metadata:
      labels: 
        app: jsp-management
    spec:
      imagePullSecrets:
      - name: huawei-key
      containers:
        - name: jsp-management
          env:
            - name: jsp-management
          image: swr.ap-southeast-3.myhuaweicloud.com/loansaas/microloan/jsp-management:v1
          imagePullPolicy: IfNotPresent
          resources: 
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 0.4
              memory: 256Mi         
--- 
apiVersion: v1
kind: Service
metadata:
  name: jsp-management-svc
  annotations:
    kubernetes.io/elb.id: 032d3c5f-bf42-4d89-82fe-51a09c0149fb
spec:
  type: LoadBalancer
  selector:
    app: jsp-management
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31083