apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsp-micro-loan
  labels:
    app: jsp-micro-loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsp-micro-loan
  template:
    metadata:
      labels: 
        app: jsp-micro-loan
    spec:
      imagePullSecrets:
      - name: huawei-key
      containers:
      - name: jsp-micro-loan
        image: swr.ap-southeast-3.myhuaweicloud.com/loansaas/microloan/jsp-micro-loan:v16
        ports:
        - containerPort: 80
        imagePullPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: jsp-micro-loan-svc
spec:
  type: NodePort
  selector:
    app: jsp-micro-loan
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 31085