apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: huawei-key
      containers:
      - name: nginx
        image: swr.ap-southeast-3.myhuaweicloud.com/loansaas/nginx/nginx:alpine
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    kubernetes.io/elb.id: 032d3c5f-bf42-4d89-82fe-51a09c0149fb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
