apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-loan-management
  labels:
    app: app-loan-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-loan-management
  template:
    metadata:
      labels: 
        app: app-loan-management
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "app-loan-management"
        dapr.io/app-port: "8083"
    spec:
      imagePullSecrets:
      - name: huawei-key
      containers:
      - name: app-loan-management
        image: swr.ap-southeast-3.myhuaweicloud.com/loansaas/microloan/app-loan-management:v1
        ports:
        - containerPort: 8083
        imagePullPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: app-loan-management-svc
spec:
  type: ClusterIP
  selector:
    app: app-loan-management
  ports:
  - port: 8083
    targetPort: 8083