apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: commission-detail
spec:
  topic: COMMISSION_DETAIL
  route: /CommissionStatistics/addDetail
  pubsubname: app-loan-management-pub-sub
scopes:
  - app-loan-management

