apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: initiate-person
spec:
  topic: INITIATE_PERSON
  route: /Person
  pubsubname: app-loan-management-pub-sub
scopes:
  - app-loan-management

