apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: loan-application-statistics
spec:
  topic: LOAN_APPLICATION_STATISTICS
  route: /LoanApplicationStatistics/addStatistics
  pubsubname: app-loan-management-pub-sub
scopes:
  - app-loan-management
