spring:
  main:
    banner-mode: "off"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: "jdbc:mysql://172.19.96.1:30306/db_saas?serverTimezone=UTC&useSSL=false"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

server:
  port : 8083

management:
  endpoints:
    web:
      exposure:
        include=*:

huawei:
  cloud:
    accessKey: "KZGUMLJ5Z9MTEGBSVVQD"
    securityKey: "01nNSdo9au0koJ39DlEFhmYnFF5EUpExG8eLJ68O"
    region: "cn-east-3"
    bucketName: "lizheng-test"

redis:
  server: 127.0.0.1:6379
  useCluster: false
  useSentinel: false
  password:

logging:
  level:
    cn.sunline.saas.huaweicloud: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%t] [%c]-[%p] %m%n"