apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: FRAUD_EVALUATION
  namespace: default
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
    - name: queueName
      value: FRAUD_EVALUATION
    - name: host
      value: amqp://admin:admin@localhost:5672
    - name: durable
      value: true
    - name: deleteWhenUnused
      value: false
    - name: ttlInSeconds
      value: 60
    - name: prefetchCount
      value: 0
    - name: exclusive
      value: false
    - name: maxPriority
      value: 5
    - name: route
      value: /FraudEvaluation