apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: loan-application-detail
spec:
  topic: LOAN_APPLICATION_DETAIL
  route: /LoanApplicationStatistics/addDetail
  pubsubname: app-loan-management-pub-sub
scopes:
  - app-loan-management

